# Generated by Django 4.0.5 on 2022-06-29 06:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('online_course', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseRegiteration',
            new_name='CourseRegistration',
        ),
        migrations.AlterModelOptions(
            name='courseregistration',
            options={'ordering': ('-student',), 'verbose_name': 'CourseRegistrations'},
        ),
        migrations.RenameField(
            model_name='courseregistration',
            old_name='regiteration_date',
            new_name='registration_date',
        ),
    ]
